idlesign/torrt

- torrt/trackers/rutracker.py
rutracker после блокировки избавился от dl.rutracker.org и отдаёт торренты с основного домена
> rutracker doesn't use dl.rutracker.org anymore

- torrt/trackers/rutracker.py
Corrected rutracker login page address
Also r-r.net preferred
> not 'login.', just 'rutracker.net/forum/login.php'

- setup.py
- torrt/base_tracker.py
- torrt/rpc/deluge.py
- torrt/rpc/transmission.py
- torrt/rpc/utorrent.py
- torrt/trackers/rutracker.py
- torrt/utils.py
- os.chmod ( http://python-future.org/compatible_idioms.html#octal-constants )
- require six library
- fix unicode problem for py3
Возможно что-то не оптимально сделал
> Feature/add support py3 [rus]

- torrt/rpc/utorrent.py
- torrt/trackers/kinozal.py
вылез косяк в py3 исправил
- Remove import urlparse in trackers/kinozal;
- Fix urljoin in rpc/utorrent ( my mistake )
> fix unused urlparse in trackers/kinozal [rus]

- torrt/trackers/rutracker.py
1. Подправил авторизацию rutracker ( они убрали ключ pushed и ориентируются на redirect )
Оставил и то и то поле, вдруг они вернут старое поле
2. Необходимо обновить пакет на https://pypi.python.org/pypi/torrt , в той версии еще не исправлен баг с подключением библиотек на py2
> fix rutracker login [rus]

- torrt/main.py
- torrt/trackers/anilibria.py
This PR fixes py3 compatibility that degraded with Anilibra's tracker addition
Also, fixes long known bug with `--verbose` flag check, that crashes app, if run without sub-command
> Restore compatibility with Python 3x, fix '--verbose' flag check

- torrt/trackers/casstudio.py
Unfortunately href regex does not working anymore. It was replaced.
> CasStudio download link was changed.

- torrt/bots/telegram_bot.py
Для того, чтобы не упереться в лимиты API Telegram, описанные в #39, объединил ответ на /list в одно сообщение.
> Single message for /list command [RUS]

- tests/trackers/test_anilibria.py
- torrt/trackers/anilibria.py
`{self.sanitize_quality(pref) for pref in self.quality_prefs}` is a set and it is not ordered. As a result torrt frequently picked quality with lower priority but higher-priority quality was available.
> Preserve user-defined quality priorities

- tests/test_utils.py
- torrt/compat.py
Made the "base64encode" method return the same result type (a sequence of bytes) whatever the python version it's run on
> Made the "base64encode" method version-agnostic

- tests/trackers/test_anilibria.py
- torrt/trackers/anilibria.py
Resolve the following problems:
1.  DDOS protection from Anilibria hosting provider
1. https://www.youtube.com/watch?v=pHlYC-aCzek
1. Choose and pick correct .torrent file when TV show is broken into several .torrent files
> Replace the way of getting Anilibria .torrent files: Anilibria website -> Anilibria API

- torrt/rpc/transmission.py
Reason: TypeError: Object of type bytes is not JSON serializable
> Cannot add new torrent to Transmission RPC

- tests/trackers/test_anilibria.py
- torrt/trackers/anilibria.py
Anilibria has a habit to publish release with highest quality first and forget about  lower quality. And when series number has more digits than the other one then we pick incorrect torrent.
See example:
1-9 [WEBRip 1080p HEVC] - incorrect pick
1-10 [WEBRip 1080p] - correct pick
> Compare string ranges as numbers

- tests/test_main.py
- torrt/base_rpc.py
- torrt/rpc/deluge.py
- torrt/rpc/qbittorrent.py
- torrt/rpc/transmission.py
- torrt/rpc/utorrent.py
- torrt/toolbox.py
Torrt always recreate a torrent and as a result doesn't preserve list of files that a user marked as "do not download".
* This is a prototype for now. Are you OK to accept the feature?
* This feature is applicable to transmission only. I'm not going to support other RPCs due to lack of API functions.
* The approach is not precise. You cannot be 100% sure that it is the same unwanted file that it was before. Hashes and names can be updated.
> Try to preserve list of unwanted files

- tests/trackers/test_rutor.py
- torrt/trackers/rutor.py
неправильно определяется Id торрента, если в SEO урле ( названии торрента ) есть символ "/" ( слеш )
```
url = 'http://rutor.info/torrent/795039/vanda/vizhn_wandavision-01h01-03-iz-09-2021-web-dl-720p-lostfilm'
splitted = url.rstrip('/').split('/')
result = splitted[-1]
if not result.isdigit():  # URL contains SEO name in the last chunk
result = splitted[-2]
print(result) // vanda, not 795039
```
> fix trackers rutor get_id_from_link seo link [RUS]

- torrt/rpc/utorrent.py
1. Поле hash возращается всегда в вверхнем регистре в utorrent;
2. В функции update_torrents нет проверки на наличие comment в rpc_torrent
> Fix method_get_torrents on utorrent rpc [RU]

- README.rst
- tests/trackers/test_ytsmx.py
- torrt/trackers/ytsmx.py
obviously, adds support for "yts.mx" tracker.
(I personally see no use in adding this tracker, as there are basically no 'updates' as in other forum-based ones, other than adding torrents from this tracker via Telegram bot. But adding it anyway)
Should satisfy #66
> add support for yts.mx tracker

- tests/trackers/test_ytsmx.py
- torrt/trackers/ytsmx.py
Didn't find any public domain movies on that tracker, so resorted to good old Matrix`91.
Also fixed BS4 warning in the same tracker test
Closes #79
> fix yts.mx tracker tests

- tests/conftest.py
- tests/test_toolbox.py
- torrt/base_bot.py
- torrt/bots/telegram_bot.py
- torrt/exceptions.py
- torrt/toolbox.py
Nice addition to #76
- bot registration now raises `BotRegistrationFailed` if there are dependencies missing.
- at launch, the user can see all the configured bots that failed to register as log warning
- `run_bots` now exits with code 1 if were were no actual bots to run. this way `systemd` (or `supervisord`) status will show whether there is something wrong with bots on the start
- ~~renamed `test_bots` to `test_bot_telegram` and made it conditional on the required package. this helps to pass tests on build servers without installing additional dependencies.~~
(duplicate of #77, as for some reason it didn't pull latest commit)
> Added non-zero exit code to run_bots if there is no bots to actually run

- .github/workflows/python-package.yml
- LICENSE
- docs/source/conf.py
- docs/source/index.rst
- setup.py
- tox.ini
- updated year (docs, license)
- dropped Python 3.6 (docs, classifiers, tests)
- updated `pytest-responsemock` (py 3.6 drop related)
Sidenotes:
After we're done with this and #78, I hope we can run `black` on the whole rep :) 
And maybe switch to poetry \ pipenv for dependency locking and stuff...
> Housekeeping 2022
